//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatic9045.DetailManagerNET.PluginTemplates.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automatic9045.DetailManagerNET.PluginTemplates.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your name and the name of your plugin. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page1Caption {
            get {
                return ResourceManager.GetString("Page1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The information entered will be used to set the assembly information, assembly name, namespace, etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page1Description {
            get {
                return ResourceManager.GetString("Page1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer name (letters and digits only, no symbols except for underscore, and no spaces) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page1DeveloperName {
            get {
                return ResourceManager.GetString("Page1DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin name  (letters and digits only, no symbols except for underscore, and no spaces) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page1PluginName {
            get {
                return ResourceManager.GetString("Page1PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assembly file name (the file name of output DLL) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page2AssemblyFileName {
            get {
                return ResourceManager.GetString("Page2AssemblyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the default namespace and assembly name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page2Caption {
            get {
                return ResourceManager.GetString("Page2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not need to make any changes, just click the &quot;Create&quot; button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page2Description {
            get {
                return ResourceManager.GetString("Page2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default namespace (letters, digits, and underscore only, no initial numerals, no C# reserved words) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page2Namespace {
            get {
                return ResourceManager.GetString("Page2Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup ATS plugin template に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BVE DetailManager.NET ATS Plugin Template Setup Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
